name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install dependencies and build
      run: cd vue-admin-template && npm install && npm run build:prod

    - name: check dist
      run: pwd && ls -l vue-admin-template

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
        cache-dependency-path: 'pet_bysj/pom.xml'
    - name: Build with Maven
      run: pwd && ls -l && mvn --file pet_bysj/pom.xml clean package -Dmaven.test.skip=true 
    - name: check jar
      run: pwd && ls -l pet_bysj/target
