name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install dependencies and build
      run: cd vue-admin-template && npm install && npm run build:prod

    - name: check dist
      run: pwd && ls -l vue-admin-template

    - name: maven build
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-args: "-DskipTests clean install"
        maven-project-folder: "pet_bysj/"
      env:
        JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/

    - name: check jar
      run: pwd && ls -l
